// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ofajbauoqcyiieajirex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mYWpiYXVvcWN5aWllYWppcmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NTU2OTUsImV4cCI6MjA4NjQzMTY5NX0.oCa16iDYeh50O_0avYfUFVTF0-sMt45wtWXTzarjkG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});