// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kehbzhcmalmqxygmhijp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaGJ6aGNtYWxtcXh5Z21oaWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDQ3NzksImV4cCI6MjA3MDQyMDc3OX0.1ET23dhxX5A8ugOPoxSb99gILGQubdQ3xmBnAXrx6zI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});